---
- name: "Initialize infrastructure"
  hosts: 
    - "{{ setup_name }}"
  vars:
    IPERF_VERSION: "foo"

  tasks:
    - name: Enable passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
      become: yes

    - name: Create connectivity testing directory
      file:
        path: ~/connectivity_testing
        state: directory

    - name: Copy tcp.sh and udp.sh files
      copy:
        src: ../scripts/{{ item }}
        dest: ~/connectivity_testing/{{ item }}
        mode: 0744
      with_items:
        - tcp.sh
        - udp.sh
    
    - name: Copy bash scripts to sendip
      copy:
        src: ../config/{{ setup_name }}/{{inventory_hostname}}_sendip.sh
        dest: ~/connectivity_testing/{{inventory_hostname}}_sendip.sh
        mode: 0744

    - name: Configure syslog
      script:
        cmd: ../config/{{ setup_name }}/{{inventory_hostname}}_syslog.sh
      become: yes

    - name: Configure iptables
      script:
        cmd: ../config/{{ setup_name }}/{{inventory_hostname}}_iptables.sh
      become: yes

    - name: Update repositories cache
      apt:
        update_cache: yes
      become: yes

    - name: Install sendip package
      package:
        name: sendip
        state: present
      become: yes
